[package]
name = "rolldown-compression"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
simd-brotli = { version = "10" }
flate2 = { version = "1.1", default-features = false, features = ["zlib-rs"] }
hotpath = "0.23"
napi = { version = "3", default-features = false, features = ["napi10", "dyn-symbols", "node_version_detect"] }
napi-derive = "3"
rayon = "1.12"
zstd = { version = "0.13", default-features = false }
anymap3 = "1"

[features]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
mimalloc = "0.1"

[target.'cfg(target_family = "wasm")'.dependencies]
zstd = { version = "0.13", default-features = false, features = ["no_asm"] }

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = { version = "0.1", features = ["local_dynamic_tls"] }

[build-dependencies]
napi-build = "2"

[profile.release]
codegen-units = 1
lto = true
strip = "symbols"
