/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Batch-wide options for [`compress_buffers`]. */
export interface BatchOptions {
  /** Worker threads; 0 or omitted = number of logical CPUs. */
  concurrency?: number
  /**
   * Mark results whose compressed size >= original as skipped and
   * return no data for them. Default: false.
   */
  skipIfLargerOrEqual?: boolean
}

/** Algorithm settings applied to every file in a batch. */
export interface CompressAlgorithm {
  /** Canonical algorithm name: "gzip" | "brotli" | "zstd". */
  algorithm: string
  /**
   * Compression level; algorithm default when omitted
   * (gzip 6, brotli 11, zstd 19).
   */
  level?: number
  /** Brotli only: log2 window size (10-24, default 22). */
  windowBits?: number
  /**
   * Brotli only: target section size in bytes when a large input is
   * split across the brotli worker pool; inputs larger than one section
   * are split. Defaults to two windows (`2^(windowBits + 1)` bytes),
   * i.e. 8 MiB at the default window.
   *
   * Smaller sections finish large files faster and cost compression
   * ratio. The encoder segments between 64 KiB and 16 MiB, and values
   * outside that range are clamped to it.
   */
  sectionSize?: number
}

/**
 * Compress a batch of buffers off the JS main thread.
 *
 * Each file carries one buffer; algorithm settings are shared by all files.
 * Results follow file order, then algorithm order within each file. Empty
 * files or algorithms arrays produce no results. Algorithm names and
 * levels are validated synchronously so misconfiguration fails fast;
 * I/O-shaped failures during compression are reported per task via
 * [`CompressResult::error`].
 */
export declare function compressBuffers(files: Array<CompressFile>, algorithms: Array<CompressAlgorithm>, options?: BatchOptions | undefined | null): Promise<Array<CompressResult>>

/** One source file, passed once regardless of the number of algorithms. */
export interface CompressFile {
  fileName: string
  data: Buffer
}

/** Outcome of a single task within a batch. */
export interface CompressResult {
  fileName: string
  algorithm: string
  /** Compressed bytes. Empty when `skipped` is true or `error` is set. */
  data: Buffer
  originalSize: number
  compressedSize: number
  /**
   * True when compression would not shrink the input and
   * `skipIfLargerOrEqual` was requested.
   */
  skipped: boolean
  /** Per-task failure. A failed task never aborts the rest of the batch. */
  error?: string
}
