/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Batch-wide options for [`compress_buffers`]. */
export interface BatchOptions {
  /** Worker threads; 0 or omitted = number of logical CPUs. */
  concurrency?: number
  /**
   * Mark results whose compressed size >= original as skipped and
   * return no data for them. Default: false.
   */
  skipIfLargerOrEqual?: boolean
}

/**
 * Compress a batch of buffers off the JS main thread.
 *
 * `tasks[i]` describes how to compress `buffers[i]`. Algorithm names and
 * levels are validated synchronously so misconfiguration fails fast;
 * I/O-shaped failures during compression are reported per task via
 * [`CompressResult::error`].
 */
export declare function compressBuffers(tasks: Array<CompressTask>, buffers: Array<Buffer>, options?: BatchOptions | undefined | null): Promise<Array<CompressResult>>

/** Outcome of a single task within a batch. */
export interface CompressResult {
  fileName: string
  algorithm: string
  /** Compressed bytes. Empty when `skipped` is true or `error` is set. */
  data: Buffer
  originalSize: number
  compressedSize: number
  /**
   * True when compression would not shrink the input and
   * `skipIfLargerOrEqual` was requested.
   */
  skipped: boolean
  /** Per-task failure. A failed task never aborts the rest of the batch. */
  error?: string
}

/**
 * One compression task: pairs with the buffer at the same index in the
 * `buffers` argument of [`compress_buffers`].
 */
export interface CompressTask {
  fileName: string
  /** Canonical algorithm name: "gzip" | "brotli" | "zstd". */
  algorithm: string
  /**
   * Compression level; algorithm default when omitted
   * (gzip 6, brotli 11, zstd 19).
   */
  level?: number
  /** Brotli only: log2 window size (10-24, default 22). */
  windowBits?: number
  /**
   * Brotli only: target section size in bytes per worker thread when
   * large inputs are split across the brotli worker pool; inputs at
   * least twice this size take the multithreaded path (default 1 MiB).
   */
  sectionSize?: number
}
